language: node_js
node_js:
  - "node"
services: 
  - postgresql
before_script:
  - psql -c 'CREATE DATABASE colors_test;' -U postgres
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: "YOUR ENCRYPTED API KEY"